version: '3'

services:
  postgres:
    build: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=1"
      - "-c"
      - "shared_preload_libraries=wal2json"
    volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql